### ISSUE TITLE
The specification describes the path of a special url as a list

### ISSUE THREAD

**Issue by lemire** [ada-url/ada#122]
It says....

>A [URL](https://url.spec.whatwg.org/#concept-url)’s path is either a [URL path segment](https://url.spec.whatwg.org/#url-path-segment) or a [list](https://infra.spec.whatwg.org/#list) of zero or more [URL path segments](https://url.spec.whatwg.org/#url-path-segment), usually identifying a location. It is initially « ». A [special](https://url.spec.whatwg.org/#is-special) [URL](https://url.spec.whatwg.org/#concept-url)’s [path](https://url.spec.whatwg.org/#concept-url-path) is always a [list](https://infra.spec.whatwg.org/#list), i.e., it is never [opaque](https://url.spec.whatwg.org/#url-opaque-path). A [URL](https://url.spec.whatwg.org/#concept-url) has an opaque path if its [path](https://url.spec.whatwg.org/#concept-url-path) is a [URL path segment](https://url.spec.whatwg.org/#url-path-segment).

Are we standard compliant ?

**Comment by lemire** [comment]
Note that if we store a path as a string with '/' delimiters, then it is not difficult to offer it as a list, if needed. You can simply have a list of string_view instances.

**Comment by anonrig** [comment]
Yes, I made this optimization to improve path state. We’re spec compliant. It was wrong for the spec. to define the data structure of a component. (and slow too)

**Comment by lemire** [comment]
We can return a list of `std::string_view` when the path is not opaque and the user desires a list. It does not need to affect the parsing performance and it can be optional. We can partition the path "on demand".

**Comment by anonrig** [comment]
Pathname getter always serializes and converts list to string by concatting the list items. There's no need to provide an API to get `list` entries.

> The pathname getter steps are to return the result of [URL path serializing](https://url.spec.whatwg.org/#url-path-serializer) [this](https://webidl.spec.whatwg.org/#this)’s [URL](https://url.spec.whatwg.org/#concept-url-url).

**Comment by anonrig** [comment]
I'm closing this, since it does not apply to our case.
