### ISSUE TITLE
We probably should not change the case of the domain

### ISSUE THREAD

**Issue by lemire** [ada-url/ada#129]
> When you receive a domain name or label, you should preserve its case.  The rationale for this choice is that we may someday need to add full binary domain names for new services; existing services would not be changed.

RFC 1034 : https://www.rfc-editor.org/rfc/rfc1034

I do not find anything at https://url.spec.whatwg.org/#url-parsing saying that we should lower the case. They refer to case-insensitve matching, but that can be accomplished by lowercasing the strings, but that's not the same thing as storing the lowercase version of the domain.

We should, similarly, check whether other strings that we manipulate should be stored with their case changed.

**Comment by anonrig** [comment]
Is there a specific test case that's holding us back from resolving this issue? If there isn't, happy to resolve this. @lemire

**Comment by lemire** [comment]
It depends on whether RFC 1034 is still considered valid.

**Comment by karwa** [comment]
Lowercasing domains is part of IDNA. It has also been a part of previous URL standards, so it is established practice. I suppose it means that specific advice from RFC-1034 is obsolete (I can't speak to whether the rest of it is still relevant).

**Comment by miguelteixeiraa** [comment]
Also:
https://github.com/web-platform-tests/wpt/blob/master/url/resources/IdnaTestV2.json#L212

```
  {
    "input": "www.eXample.cOm",
    "output": "www.example.com"
  }
```
So I think we are probably good changing the case of the domain.

**Comment by lemire** [comment]
> So I think we are probably good changing the case of the domain.

Well. Yeah. I am going to close this issue, but the fact that the output is in lower case does not imply that we ought to discard the case.

Still, I think that we will discard it.
