### ISSUE TITLE
Simplify set_host and set_hostname

### ISSUE THREAD

**Issue by anonrig** [ada-url/ada#131]
Both of them have the same code, except for a single line:

```
If state override is given and state override is [hostname state](https://url.spec.whatwg.org/#hostname-state), then return.
```

**Comment by debadree25** [comment]
I moving the definition into helpers acceptable?

**Comment by anonrig** [comment]
Sounds good @debadree25. Go for it! Remember, let's have one function that both `set_host` and `set_hostname` calls

**Comment by debadree25** [comment]
Sure enough! will try to submit a PR in next day or two
