### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by lemire** [ada-url/ada#133]
This project needs a logo.

**Comment by anonrig** [comment]
Ada means "island" in Turkish. What do you think about a minimalistic island as an icon?

**Comment by lemire** [comment]
Go! Anything is better than nothing.

**Comment by anonrig** [comment]
![ada-icon](https://user-images.githubusercontent.com/1935246/215625152-8ab6b7ac-84d9-4e86-b2d1-55beb479d213.png)

**Comment by lemire** [comment]
Let us go!

**Comment by anonrig** [comment]
Done!
