### ISSUE TITLE
Provide a way to construct ada::url from a struct

### ISSUE THREAD

**Issue by anonrig** [ada-url/ada#140]
For example Node uses the following struct. We need to construct a `ada::url` from a struct. If we use `ada::url value;` and then use `value.set_port()` it might not work, since there are limitations on the setters side. (For example, you can't set `port` if `host` does not have a value etc. This needs to also properly set the private variables inside our `ada::url` struct.

```
struct url {
  int32_t flags = URL_FLAGS_NONE;
  int port = -1;
  std::string scheme;
  std::string username;
  std::string password;
  std::string host;
  std::string query;
  std::string fragment;
  std::vector<std::string> path;
  std::string href;
};
```

with the following flags:

```
#define FLAGS(XX)                                                             \
  XX(URL_FLAGS_NONE, 0)                                                       \
  XX(URL_FLAGS_FAILED, 0x01)                                                  \
  XX(URL_FLAGS_CANNOT_BE_BASE, 0x02)                                          \
  XX(URL_FLAGS_INVALID_PARSE_STATE, 0x04)                                     \
  XX(URL_FLAGS_TERMINATED, 0x08)                                              \
  XX(URL_FLAGS_SPECIAL, 0x10)                                                 \
  XX(URL_FLAGS_HAS_USERNAME, 0x20)                                            \
  XX(URL_FLAGS_HAS_PASSWORD, 0x40)                                            \
  XX(URL_FLAGS_HAS_HOST, 0x80)                                                \
  XX(URL_FLAGS_HAS_PATH, 0x100)                                               \
  XX(URL_FLAGS_HAS_QUERY, 0x200)                                              \
  XX(URL_FLAGS_HAS_FRAGMENT, 0x400)                                           \
  XX(URL_FLAGS_IS_DEFAULT_SCHEME_PORT, 0x800)                                 \
```

**Comment by lemire** [comment]
The `std::vector<std::string> path;` attribute is related to https://github.com/ada-url/ada/issues/122 That is, a non-opaque path is supposed to be a list (here `std::vector<std::string> path;`), but `std::vector<std::string> path;`  is possibly a non-ideal choice: we can simply enumerate from a single string using std::string_view instances.

The `flags` parameter is a nice way to avoid things like `std::optional` but it is not strictly better. It leads to a struct that is slightly smaller, by say 8 bytes... than the ada::url struct... but these structs are ~ 256 bytes to begin with... so it is not significant.

**Comment by anonrig** [comment]
- `std::vector<std::string> path` is still unnecessary, and will be replaced with `std::string` since node.js already does this on the javascript side (it never exposes vector value to the userland.)
- Node.js functions return [`struct url_data`](https://github.com/nodejs/node/blob/main/src/node_url.h#L64) to the javascript side, and then depending on the action, updates the state on the [javascript side](https://github.com/nodejs/node/blob/main/lib/internal/url.js#L545). I can return the object but `is_special` kind of getter variables, are not stored within our architecture. I might introduce a layer on top of Ada to provide those fields before passing it into the JS layer, but I'm still investigating...

**Comment by anonrig** [comment]
I think the correct implementation is to have a constructor of `ada::url` which allows us to directly set the values for `username`, `password`, `host` etc. without going through the parser.

**Comment by anonrig** [comment]
Closing this. It's not needed.
