### ISSUE TITLE
`http://./` is a valid url

### ISSUE THREAD

**Issue by anonrig** [ada-url/ada#146]
`http://./` as an input is valid for both safari & chrome, but it's invalid for us.

**Comment by anonrig** [comment]
I'm reopening this because we were skipping this URL in the input, but we shouldn't have.

**Comment by lemire** [comment]
Why? The standard is clear on this. Labels must be between 1 and 63 bytes. If we misread the standard, can you quote the relevant section?

**Comment by anonrig** [comment]
I've not looked into the spec for this, but: there is a particular section in WPT labeled "domains with empty labels": https://github.com/web-platform-tests/wpt/blob/master/url/resources/urltestdata.json#L3889

**Comment by lemire** [comment]
RFC 1034: Internally, programs that manipulate domain names should represent them
as sequences of labels, where each label is a length octet followed by
an octet string.  Because all domain names end at the root, which has a
null string for a label, these internal representations can use a length
byte of zero to terminate a domain name.

**Comment by lemire** [comment]
One label is reserved, and that is
the null (i.e., zero length) label used for the root.

**Comment by lemire** [comment]
A label may contain zero to 63 characters. The null label, of length zero, is reserved for the root zone. https://en.m.wikipedia.org/wiki/Domain_Name_System

**Comment by anonrig** [comment]
Can you open an issue to the web-platform-tests repository? Even though you're right, removing this test from the Node repository without changing the WPT won't be possible.

**Comment by lemire** [comment]
"The hierarchy of domains descends from the right to the left label in the name; each label to the left specifies a subdivision, or [subdomain](https://en.m.wikipedia.org/wiki/Subdomain) of the domain to the right. For example: the label example specifies a node example.com as a subdomain of the com domain, and www is a label to create www.example.com, a subdomain of example.com. Each label may contain from 1 to 63 [octets](https://en.m.wikipedia.org/wiki/Octet_(computing)). The empty label is reserved for the root node and when fully qualified is expressed as the empty label terminated by a [dot](https://en.m.wikipedia.org/wiki/Full_stop). The full domain name may not exceed a total length of 253 ASCII characters in its textual representation.” https://en.m.wikipedia.org/wiki/Domain_name

**Comment by lemire** [comment]
Seems related to this: https://github.com/servo/rust-url/issues/554

So something can be an invalid URL, but still pass through the algorithm.

**Comment by miguelteixeiraa** [comment]
About the link that Yagiz provided ([WPT tests](https://github.com/web-platform-tests/wpt/blob/master/url/resources/urltestdata.json#L3889)),

All the tests/examples of the section mentioned (**domains with empty labels**) are not **FQDN** (fully qualified domain names) 
 To be considered FQDN, the domain name must include a Second-Level Domain (**SLD**) and a Top-Level Domain (**TLD**).

An example of FQDN is www.example.com, where "www" is the hostname (not required), "example" is the second-level domain (SLD), and ".com" is the top-level domain (TLD).

**Comment by miguelteixeiraa** [comment]
I'm looking for references that state these limits/sizes/rules only apply to FQDNs.

**Comment by miguelteixeiraa** [comment]
> I'm looking for references that state these limits/sizes/rules only apply to FQDNs.

I couldn't find anything

**Comment by lemire** [comment]
@miguelteixeiraa  I think we should add a method to the URL struct such as `bool is_fully_qualified_domain_name() const` and that method would check that it is indeed a Fully qualified domain name, possibly adding other checks.

> I'm looking for references that state these limits/sizes/rules only apply to FQDNs.

I don't think they do.

> apply the rules only when there is the basic structure to be a fqdn (at least 2 non-zero labels) )

My proposal is rather to parse successfully the URL, irrespective of label lengths and so forth, but to have a method like `is_valid_domain() const` that does additional checks.

**Comment by lemire** [comment]
@anonrig I don't think that `http://./ ` is a valid URL. To prove me wrong, please register it. I don't think you can.

It is a valid URL string as per https://url.spec.whatwg.org/ But that link mentions RFC 1034 only once, in passing, and does not appear to try to abide by it at all.

**Comment by lemire** [comment]
To be clear, I still think it is fine to accept to parse it…

**Comment by lemire** [comment]
@anonrig 

Is this resolved?

**Comment by anonrig** [comment]
We can close this for now 👍
