### ISSUE TITLE
Simplify parse_url 

### ISSUE THREAD

**Issue by lemire** [ada-url/ada#171]
The current implementation of parse_url does not have an ideal implementation as far as maintainability is concerned.

- We started out with `std::string_view::iterator` instances. The finite state machine would sometimes decrement the iterators before the string start, only to soon increment it.
- We fixed this by short-circuiting the design with direct jumps.
- In a later PR, we removed the  `std::string_view::iterator` and now work with with integers (`input_position`). The integer is maintained in a range between 0 and the input length (inclusively).

@ronag proposed what I feel is a better design at: https://github.com/ada-url/ada/pull/169

Instead of systematically incrementing the integer position with each pass, he just expects the states to increment as needed. This is simpler because we don't need to decrement and then reincrement.

It should be possible to implement parse_url in a forward-only design (where you never go back, you only go forward).

Alternatively, it could be implemented with a string_view that gets shorter and shorter.

**Comment by anonrig** [comment]
I'll take a look at this, if you didn't start working on it.
