### ISSUE TITLE
Logger calls decrease performance

### ISSUE THREAD

**Issue by anonrig** [ada-url/ada#174]
Lines like `ada_log("RELATIVE_SLASH ", helpers::substring(url_data, input_position));` reduces performance. We should trim `ada_log` calls from production builds (and from benchmarks).

**Comment by lemire** [comment]
Unlikely. It is not a function, but a macro. At *compile time*, the macro replaces `ada_log("RELATIVE_SLASH ", helpers::substring(url_data, input_position));` with *nothing*. To be clear, the macro gets processed *before* the C++ compiler does its work, so the C++ compiler does not even see what was in the macro !

If you compile this...

```C++
#include <string_view>
#include <string>

#if ADA_LOGGING

#ifndef ada_log
#define ada_log(...) do { \
    ada::log(__VA_ARGS__); \
} while(0)
#endif // ada_log
#else
#define ada_log(...)
#endif // ADA_LOGGING

void increment(std::string_view v) {
    ada_log(std::string(v) + ":", "joe");
}
```

The increment function is the empty function.

More fun... let us pass ada_log something that cannot possibly compile like ... `std::string_doesnotexist(v) ":", +"joe"sffdsfdsfdsfds`.


```C++
#include <string_view>
#include <string>

#if ADA_LOGGING

#ifndef ada_log
#define ada_log(...) do { \
    ada::log(__VA_ARGS__); \
} while(0)
#endif // ada_log
#else
#define ada_log(...)
#endif // ADA_LOGGING

void increment(std::string_view v) {
    ada_log(std::string_doesnotexist(v) ":", +"joe"sffdsfdsfdsfds);
}
```

It will work just fine!!!

Try it. Replace `ada_log("RELATIVE_SLASH ", helpers::substring(url_data, input_position))` by some nonesense like `ada_log("RELATIVE_SLASH ", ssssssshelpers::mysubstring(url_data, input_position))` and you will see that it still builds.

**Comment by anonrig** [comment]
Amazing. Thanks. It was bugging me for a while.
