### ISSUE TITLE
Create C Interface

### ISSUE THREAD

**Issue by lemire** [ada-url/ada#201]
We might want C users to be able to use ada.

See https://github.com/ada-url/ada_c_demo for a sketch.

**Comment by ityashag** [comment]
Hi, I would like to contribute to it. can you tell me more about the issue?

**Comment by lemire** [comment]
@ityashag Contribution welcome. Ada is a C++17 project. Some users might want to call it from C.  The way you achieve this generally is with `extern "C"` sections, which allow you to write C code that C users will see, while they won't have access to the C++ code.


 The task is to prepare a C interface (that can be called from C) of ada, test it and document it. I believe my code above is a good sketch. You could start working on it and see how far you go. No need to solve everything. Just go as far as you can and then ping us.

**Comment by ityashag** [comment]
Hi, this is my first try at the problem. what I understood from the above message is that I need to create a c equivalent code for the one you have written; below is the implementation.
if  I had understood something wrong please correct me I am ready to work on it. 
please guide me what to do next.


`#ifndef ADA_H
#define ADA_H

#include "ada.h"

typedef struct ada_result ada_result;

ada_result* ada_parse(char * string);
int ada_is_valid(ada_result * result);
void ada_free(ada_result * result);
const char* ada_get_scheme(ada_result * result);

ada_result* ada_parse(char* string) {
    ada_result* result = (ada_result*)malloc(sizeof(ada_result));
    result->r = ada::parse(string);
    return result;
}

void ada_free(ada_result * result) {
    free(result);
}

int ada_is_valid(ada_result * result) {
    return (int)bool(result->r);
}

const char* ada_get_scheme(ada_result * result) {
    if (!bool(result->r)) {
        return NULL;
    }
    return result->r.get_scheme().data();
}

#endif`

**Comment by lemire** [comment]
Please see https://github.com/ada-url/ada_c_demo where I have a minimal demo that actually works. We need to complete it (tests, documentation, integration with the main project and so forth).

**Comment by lemire** [comment]
@anonrig Are we happy? Do we close this?

**Comment by anonrig** [comment]
Yes, definitely!
