### ISSUE TITLE
Add WPT runner

### ISSUE THREAD

**Issue by anonrig** [ada-url/ada#3]
We need a WPT runner to understand where we are and what kind of errors we have. [This commit](https://github.com/ada-url/ada/pull/2/commits/55afd0516b869a83215bde0a786278325f62bac2) has a script to update the results from the Git repository of WPT. It would be satisfactory if we can parse the JSON and run the tests according to each object.

**Comment by lemire** [comment]
I could help with this after https://github.com/ada-url/ada/pull/2 is merged.
