### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by anonrig** [ada-url/ada#4]
Supported states:

- [x] AUTHORITY - https://github.com/ada-url/ada/pull/14
- [x] SCHEME_START - https://github.com/ada-url/ada/pull/2
- [x] SCHEME - https://github.com/ada-url/ada/pull/2
- [x] HOST - https://github.com/ada-url/ada/pull/12
- [x] NO_SCHEME - https://github.com/ada-url/ada/pull/14
- [x] FRAGMENT - https://github.com/ada-url/ada/pull/12
- [x] RELATIVE - https://github.com/ada-url/ada/pull/14
- [x] RELATIVE_SLASH - https://github.com/ada-url/ada/pull/8
- [x] FILE - https://github.com/ada-url/ada/pull/14
- [x] FILE_HOST - https://github.com/ada-url/ada/pull/14
- [x] FILE_SLASH - https://github.com/ada-url/ada/pull/14
- [x] PATH_OR_AUTHORITY - https://github.com/ada-url/ada/pull/8
- [x] SPECIAL_AUTHORITY_IGNORE_SLASHES - https://github.com/ada-url/ada/pull/8
- [x] SPECIAL_AUTHORITY_SLASHES - https://github.com/ada-url/ada/pull/8
- [x] SPECIAL_RELATIVE_OR_AUTHORITY - https://github.com/ada-url/ada/pull/8
- [x] QUERY - https://github.com/ada-url/ada/pull/12
- [x] PATH - https://github.com/ada-url/ada/pull/14
- [x] PATH_START - https://github.com/ada-url/ada/pull/14
- [x] OPAQUE_PATH - https://github.com/ada-url/ada/pull/13
- [x] PORT - https://github.com/ada-url/ada/pull/14

**Comment by lemire** [comment]
See https://github.com/ada-url/ada/projects
