### ISSUE TITLE
Do you have a precompiled binary for centos 7 linux?

### ISSUE THREAD

**Issue by rstorch01** [ada-url/ada#467]
### What is the problem this feature will solve?

Will help install.

### What is the feature you are proposing to solve the problem?

Trying to install

### What alternatives have you considered?

Asking you about the binary.

**Comment by anonrig** [comment]
We don't have a precompiled binary for centos 7, but you can build it depending on your needs easily. We have an extensive documentation on building: https://www.ada-url.com/docs/installation#compiling

**Comment by lemire** [comment]
Ada is available for some Linux distributions such as [alpine](https://alpine.pkgs.org/3.19/alpine-main-aarch64/ada-dev-2.7.4-r0.apk.html). It is available through [vcpkg.json](https://github.com/microsoft/vcpkg/blob/9765877106f7c179995e8010bb7427a865a6bd1d/ports/ada-url/vcpkg.json#L2),  [conan](https://conan.io/center/recipes/ada?version=2.7.7) and various other package managers.

If you want an ada package for your specific Linux distribution, you need to ask the distribution in question. They have to choose to adopt ada. We do not make this decision. We will support them, however.


Regarding CentOS specifically, its last release was in 2021 and then RedHat terminated it. It is considered legacy at this point. I recommend you update to something like RockyLinux or RedHat itself if you need the support.
