### ISSUE TITLE
Unicode RGI Emoji ZWJ Sequences / WhatWG URL / CheckJoiners

### ISSUE THREAD

**Issue by adraffy** [ada-url/ada#510]
How do you encode an Emoji ZWJ Sequence with Ada?  

There are 3K+ RGI emoji and 39% of them involve ZWJ sequences.  From Unicode's front page:
> 92% of the world’s online population use emoji in their communications

The WhatWG URL decision to use `CheckJoiners` was [shortsighted.](https://github.com/whatwg/url/issues/776)  

### What is the feature you are proposing to solve the problem?

`CheckJoiners` should be **`false`**.

**Comment by lemire** [comment]
The WHATWG URL standard states:

> Let result be the result of running [Unicode ToASCII](https://www.unicode.org/reports/tr46/#ToASCII) with domain_name set to domain, UseSTD3ASCIIRules set to beStrict, CheckHyphens set to false, CheckBidi set to true, CheckJoiners set to true, Transitional_Processing set to false, and VerifyDnsLength set to beStrict. [[UTS46]](https://url.spec.whatwg.org/#biblio-uts46)

The ada library is an implementation of the WHATWG URL standard. We do not set the standard nor do we set out to change the standard.

You may disagree with the standard, and be right that it is incorrect. If so, you should get the standard to change. If the standard changes, we will adapt the implementation.

I am closing this issue. The reported should open an issue with the WHATWG URL standard instead.
