### ISSUE TITLE
Add ARM-based testing with sanitizers in continuous integration

### ISSUE THREAD

**Issue by lemire** [ada-url/ada#520]
Currently, we run benchmarks with sanitizers in CI only on x64 hardware:

https://github.com/ada-url/ada/blob/main/.github/workflows/ubuntu-sanitized.yml

We need to add ARM-based sanitized tests to avoid issues such as https://github.com/ada-url/ada/pull/519 and https://github.com/nodejs/node/issues/49960

**Comment by CarlosEduR** [comment]
We'd need something like this, right, @lemire? https://github.com/marketplace/actions/arm-runner

I am interested in colaborating, just checking more about the options we have to use ARM.

**Comment by lemire** [comment]
More like this: https://github.com/simdutf/simdutf/blob/master/.github/workflows/aarch64.yml
