### ISSUE TITLE
Questionable premature optimizations?

### ISSUE THREAD

**Issue by the-moisrex** [ada-url/ada#547]
All `find_next_host_delimiter_special` and `find_next_host_delimiter` are doing is a simple search which could've been done using a lookup table.

https://github.com/ada-url/ada/blob/a9dd0d427e965ade856306c0e4b0afca04292db1/src/helpers.cpp#L203-L325

Trying to make it easy for the compiler to SIMDIfy it has backfired.

[Ada's version assembly](https://godbolt.org/z/6oevh5ndx) (which by the way, it won't vectorize until you specify `-march=native` or a-likes)
[Table Lookup generated assembly](https://godbolt.org/z/GbrG7W4G6)
[Benchmarks](https://github.com/the-moisrex/webpp/tree/99b5c837c6aabe7bee8629e001b61b66e62d2ec9/benchmarks/charset)

```
--------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations
--------------------------------------------------------------------
AdaAutoVectorizedSolution       25.7 ns         25.7 ns    174780063
WebppSimpleCharsetSearch        28.3 ns         28.2 ns    148920655
WebppSimpleCharmapSearch        15.9 ns         15.9 ns    265948817
```

Is there a reason why you have gone into such a trouble of optimizing it this way? Am I missing something or is this a clear premature optimization situation?

**Comment by lemire** [comment]
You are correct that we can gain a bit more speed by more carefully vectorizing the code.

I did so in ...
https://github.com/ada-url/ada/pull/548

However, my results do not agree with your suggestion that it is premature optimization. Using character-by-character processing leads to a significant performance drop.

If you disagree, could you modify our code, build "benchdata" and run it before and after your change? We care about `BasicBench_AdaURL_aggregator_href` (other components of the benchmark will not be impacted).

**Comment by the-moisrex** [comment]
Simple lookup table is faster, your PR is even faster than that.

It doesn't affect the overall parsing performance too much; the benchmark gives me too much noise on my machine.

`ada-url` is using everything all over the place. For example `character_sets-inl.h` is essentially doing what `std::bitset` (and `webpp::bitmap`) is doing, while here we're doing the same thing manually with bit manipulation, and trying to SIMDify or Simplify it.

It lacks consistency.

#### A note about CharSet:

My `webpp::charset`, `webpp::charmap`, and `webpp::bitmap` (I know, not the best names) unifies this and you can switch between them quickly, though I don't think it required for this project to contain such thing.

I might add a SIMDified version of these features as well to see the difference, but them being generalized, I can easily switch them trivially later if I see it's better.

**Comment by lemire** [comment]
It does seem like we can improve the performance of this code. Thanks.
