### ISSUE TITLE
Non-special URIs with hosts

### ISSUE THREAD

**Issue by the-moisrex** [ada-url/ada#558]
Ada gives

```
urn://this/is/a/path
    | |   |         
    | |   `--------- pathname_start 10
    | |   `--------- host_end 10
    | `------------- host_start 6
    | `------------- username_end 6
    `--------------- protocol_end 4
```

while `//this/is/a/path` is a path not a host.

![image](https://github.com/ada-url/ada/assets/12122474/94697d27-9e4f-40c6-9d4e-5e84c225ed13)

**Comment by the-moisrex** [comment]
Also straight out of [RFC example](https://www.rfc-editor.org/rfc/rfc3986#section-1.1.2) which just confused me:

```
ldap://[2001:db8::7]/c=GB?objectClass?one
     | |            |    |               
     | |            |    `--------------- search_start 25
     | |            `-------------------- pathname_start 20
     | |            `-------------------- host_end 20
     | `--------------------------------- host_start 7
     | `--------------------------------- username_end 7
     `----------------------------------- protocol_end 5
```

![image](https://github.com/ada-url/ada/assets/12122474/7589d95a-b3a5-410d-9039-81b2fa970969)


It confused me because the [WHATWG parser says](https://url.spec.whatwg.org/#scheme-state):

> 7 - Otherwise, if url [is special](https://url.spec.whatwg.org/#is-special), set state to [special authority slashes state](https://url.spec.whatwg.org/#special-authority-slashes-state).
> 8 - Otherwise, **if [remaining](https://url.spec.whatwg.org/#remaining) starts with an U+002F (/), set state to [path or authority state](https://url.spec.whatwg.org/#path-or-authority-state)** and increase pointer by 1.
> 9 - Otherwise, set url’s [path](https://url.spec.whatwg.org/#concept-url-path) to the empty string and set state to [opaque path state](https://url.spec.whatwg.org/#cannot-be-a-base-url-path-state).

It sets it to **path or authority** state if the URL is not special; which is what WHATWG says, but not what browser's implementations do, and I can't find any proof that "//" on non-special schemes would mean it's an authority start or not in the RFC.

**Comment by lemire** [comment]
Here is what my browser (WebKit) does:

<img width="887" alt="Capture d’écran, le 2023-11-09 à 09 02 16" src="https://github.com/ada-url/ada/assets/391987/78c90559-f6f0-4423-a2f9-3979048a827d">
<img width="840" alt="Capture d’écran, le 2023-11-09 à 09 13 51" src="https://github.com/ada-url/ada/assets/391987/aa7c03c1-3286-4f82-ad95-d8a86d1d8219">

... which matches what ada does, doesn't it?

Our reference is WHATWG URL. Can you indicate what is the issue in ada while making a reference to WHATWG URL?

If you think that the WHATWG URL specification is incorrect, then you need to take this with them.

We will only change ada if we find that we are not following the specification. 

Please elaborate on what the issue.

**Comment by the-moisrex** [comment]
WHATWG says what ada already does; I guess I expected chromium and firefox's implementations be WHATWG compliant, but there seem to be a difference here.

![image](https://github.com/ada-url/ada/assets/12122474/93f695e0-fcb4-460b-9638-45478ca9da54)

**Comment by anonrig** [comment]
@the-moisrex Somewhat similar blog post of mine: https://www.yagiz.co/url-parsing-and-browser-differences
