### ISSUE TITLE
set_protocol("https:") does not work when constructing new url

### ISSUE THREAD

**Issue by sfionov** [ada-url/ada#573]
### Version

2.7.4

### Platform

macos

### What steps will reproduce the bug?

```
ada::url url;
url.set_protocol("https");
url.set_host("google.com");
return url.get_href();
```
or
```
ada::url_aggregator url;
url.set_protocol("https");
url.set_host("google.com");
return url.get_href();
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

```
https://google.com
```

### What do you see instead?

```
//google.com
```

**Comment by sfionov** [comment]
Found workaround: `url.type = ada::scheme::HTTPS`, but there is no workaround for `url_aggregator`.

**Comment by lemire** [comment]
We follow the WHATWG URL specification.

Here is what the protocol setter should do:


> The [protocol](https://url.spec.whatwg.org/#dom-url-protocol) setter steps are to [basic URL parse](https://url.spec.whatwg.org/#concept-basic-url-parser) the given value, followed by U+003A (:), with [this](https://webidl.spec.whatwg.org/#this)’s [URL](https://url.spec.whatwg.org/#concept-url-url) as [url](https://url.spec.whatwg.org/#basic-url-parser-url) and [scheme start state](https://url.spec.whatwg.org/#scheme-start-state) as [state override](https://url.spec.whatwg.org/#basic-url-parser-state-override).


In turn this points at ...




> scheme state
> If [c](https://url.spec.whatwg.org/#c) is an [ASCII alphanumeric](https://infra.spec.whatwg.org/#ascii-alphanumeric), U+002B (+), U+002D (-), or U+002E (.), append [c](https://url.spec.whatwg.org/#c), [lowercased](https://infra.spec.whatwg.org/#ascii-lowercase), to buffer.
> 
> Otherwise, if [c](https://url.spec.whatwg.org/#c) is U+003A (:), then:
> 
> If state override is given, then:
> 
> If url’s [scheme](https://url.spec.whatwg.org/#concept-url-scheme) is a [special scheme](https://url.spec.whatwg.org/#special-scheme) and buffer is not a [special scheme](https://url.spec.whatwg.org/#special-scheme), then return.
> 
> If url’s [scheme](https://url.spec.whatwg.org/#concept-url-scheme) is not a [special scheme](https://url.spec.whatwg.org/#special-scheme) and buffer is a [special scheme](https://url.spec.whatwg.org/#special-scheme), then return.
> 
> If url [includes credentials](https://url.spec.whatwg.org/#include-credentials) or has a non-null [port](https://url.spec.whatwg.org/#concept-url-port), and buffer is "file", then return.
> 
> If url’s [scheme](https://url.spec.whatwg.org/#concept-url-scheme) is "file" and its [host](https://url.spec.whatwg.org/#concept-url-host) is an [empty host](https://url.spec.whatwg.org/#empty-host), then return.
> 
> Set url’s [scheme](https://url.spec.whatwg.org/#concept-url-scheme) to buffer.
> 


Pay attention to this condition:

>  If url’s [scheme](https://url.spec.whatwg.org/#concept-url-scheme) is a [special scheme](https://url.spec.whatwg.org/#special-scheme) and buffer is not a [special scheme](https://url.spec.whatwg.org/#special-scheme), then return.

It is your scenario. By my reading, the specification tells us to just return and effectively ignore your protocol-setting request.

We are eager to correct bugs, if there are bugs, but you must argue in relation to the specification :

https://url.spec.whatwg.org/#dom-url-protocol

If you think that the specification is wrong, then it needs to be taken up with WHATWG.

**Comment by sfionov** [comment]
Thanks for clarification! Using the constructor from the URL string as stated in spec solves my problem.
