### ISSUE TITLE
Missing `percent_encode<true>` symbol (on MacOS/clang)

### ISSUE THREAD

**Issue by feltech** [ada-url/ada#580]
### Version

2.7.4

### Platform

Darwin FWAMM008.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64

### What steps will reproduce the bug?

Linking `libada.a` into a MacOS binary that uses `ada::unicode::percent_encode<true>`

### How often does it reproduce? Is there a required condition?

Windows and Linux (Ubuntu) seem fine.  MacOS x86 and ARM both fail though. So presumably it's a `clang` thing.

### What is the expected behavior?

Linking succeeds.

### What do you see instead?

```
undef: __ZN3ada7unicode14percent_encodeILb1EEEbNSt3__117basic_string_viewIcNS2_11char_traitsIcEEEEPKhRNS2_12basic_stringIcS5_NS2_9allocatorIcEEEE
Undefined symbols for architecture arm64:
  "bool ada::unicode::percent_encode<true>(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&)", referenced from:
      openassetio::v1::utils::FileUrlPathConverterImpl::pathToUrl(std::__1::basic_string_view<char, std::__1::char_traits<char>>, openassetio::v1::utils::PathType) in lto.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Additional information

```
$ nm --demangle libada.a | grep percent_encode
0000000000004608 T ada::unicode::percent_encode(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned char const*)
0000000000004ab0 T ada::unicode::percent_encode(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned char const*, unsigned long)
0000000000024b00 T bool ada::unicode::percent_encode<false>(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)
```

Note the lack of `percent_encode<true>` (only `false`)

I note via a GitHub search that `ada::unicode::percent_encode<false>` is used within Ada's own codebase, so is instantiated, whereas the `true` specialisation is never used.  So I suspect it's just never generated in the library binary.

**Comment by anonrig** [comment]
@lemire Any idea how to prevent this?

**Comment by feltech** [comment]
For context, I came across this whilst writing `file://`<->path conversion functions, so unless/until #309 is implemented having Ada do the percent decoding for us is _really_ handy :wink: 

In particular, it is required to _not_ percent-encode the beginning of some URLs (`file:///C:`). So the template specialisation in question, which conditionally appends if percent-encoding is required, fit the bill.

**Comment by lemire** [comment]
I agree that solving issue 309  is desirable but the step forward is to actually go ahead and implement it in ada. Right?

Exposing dirty bits seems like a step backward.
