### ISSUE TITLE
Capacity does not indicate the safe buffer size

### ISSUE THREAD

**Issue by lemire** [ada-url/ada#64]
The convention in the C++ runtime is that capacity() is merely an indication of the memory allocation that might have been done. However, it is not considered safe to write to this memory as far as I know.

Potentially unsafe usage:
https://github.com/ada-url/ada/blob/e79260ca4cce3e2db580a38151e179b4dc701bf8/src/parser.cpp#L53

**Comment by anonrig** [comment]
You are absolutely right. The latest pull request fixed this issue. Closing it.
