### ISSUE TITLE
Benchmarks doesn't run on Windows

### ISSUE THREAD

**Issue by anonrig** [ada-url/ada#650]
We should make our benchmarks run on Windows to open room for optimizations. 

cc @lemire

**Comment by lemire** [comment]
They work for me, except for the part where the Rust integration breaks, but we can just disable it: https://github.com/ada-url/ada/pull/651

**Comment by lemire** [comment]
@anonrig Does it work for you now that https://github.com/ada-url/ada/pull/651 is merged? If so, I recommend closing this issue. Or changing its title.

**Comment by anonrig** [comment]
@lemire Thanks. It seems it fixes the issue for me. Currently, cmake detects MSVC as the compiler to build and compile Ada for me on Windows. The question is how do you execute benchmarks on Windows? There is no .exe file?

**Comment by lemire** [comment]
@anonrig There should be... it should be in `build/benchmarks/Release/something.exe` or `build/benchmarks/Debug/something.exe` depending on how you invoked `cmake --build` (e.g., `cmake --build build --config Release` or something like it.).

(Note that my instructions can be slightly wrong, I did not check.)

**Comment by lemire** [comment]
There definitively should `.exe` files. It slightly different from mac/linux in that you need to specify release/debug  and the release/debug files are in different locations.
