### ISSUE TITLE
Let's consider dropping ada_url::url in next major

### ISSUE THREAD

**Issue by anonrig** [ada-url/ada#654]
Url aggregator is the mostly used parser. Let us consider dropping url for the next major and maybe calling it url? 

This would simplify codebase a lot and make our jobs easier for can parse, as well as urlpattern?

**Comment by anonrig** [comment]
cc @lemire what do you think?

**Comment by lemire** [comment]
@anonrig Hmmm... We should always have some care before introducing a breaking change.

How sure are we that there is no user? If we can be certain that nobody uses it, then I am all for pruning it.

But let us not break people's code without warning !!!

**Comment by jasnell** [comment]
Strongly recommend taking things through a proper deprecation cycle on stuff like this.

**Comment by anonrig** [comment]
> Strongly recommend taking things through a proper deprecation cycle on stuff like this.

Which deprecation cycle do you recommend we follow? I think first we need to document that.

**Comment by lemire** [comment]
This goes a bit against my proposal to use the fact that we have two functionally equivalent implementations to improve testing.

**Comment by anonrig** [comment]
While improving `ada::can_parse`, I realized that `if constexpr (XXX)` have 50-60ns performance impact per URL.

**Comment by lemire** [comment]
@anonrig We we can do `if constexpr`, then we definitively should... it makes the code cleaner.
