### ISSUE TITLE
Many WHATWG URL conformance tests fail

### ISSUE THREAD

**Issue by 0xg0nz0** [ada-url/ada#703]
### Version

2.7.7

### Platform

Linux 40be6416ee1d 6.6.32-linuxkit #1 SMP Thu Jun 13 14:13:01 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### What steps will reproduce the bug?

Extract all URL's from https://raw.githubusercontent.com/web-platform-tests/wpt/master/url/resources/urltestdata.json; the first five are fine, but if you run even just top 10, you'll core dump.

### How often does it reproduce? Is there a required condition?

Fully reproducible.

### What is the expected behavior?

Since ada-url indicates it follows WHATWG, I would expect all the WHATWG test cases to pass.

### What do you see instead?

See above: I expect all conformance tests to pass. To illustrate with a screen shot:

![errors](https://github.com/user-attachments/assets/67e267ae-38d9-4204-9a63-92f3e4a019e9)

The error when parsing the `:foo.com` test case is a SIGABRT due to a failed assertion:

```
constexpr T* tl::expected<T, E>::operator->() [with T = ada::url; E = ada::errors]: Assertion `has_value()' failed.
```

**Comment by anonrig** [comment]
Hi @0xg0nz0,

We already run all tests on "urltestdata.json". Please look at to the implementation at: https://github.com/ada-url/ada/blob/main/tests/wpt_tests.cpp#L48.

I don't know how you run the web-platform tests, but if you think there is a bug with out web-platform tests runner, we are more than happy to fix it.

PS: Node.js uses Ada and has a built-in up-to date WPT runner, which doesn't have any issues at the moment.

**Comment by anonrig** [comment]
You can also find the WPT fixtures at https://github.com/ada-url/ada/tree/main/tests/wpt

**Comment by anonrig** [comment]
Here's the `stable` node.js web-platform tests results: https://wpt.fyi/results/url?label=master&label=stable&product=node.js&aligned

**Comment by 0xg0nz0** [comment]
Thanks @anonrig, I will see if I can figure out what's different about my test runner -- all it's doing is downloading urltestdata.json and parsing each input URL.

**Comment by anonrig** [comment]
No worries. If there is a specific bug in Ada, please feel free to open a new issue and I'll fix it asap.

**Comment by 0xg0nz0** [comment]
My hunch is it's something in the JSON parser I am using, maybe it's passing an incorrectly-translated string for "\t   :foo.com   \n" -- seems plausible, I will see if I can get to the bottom of it.

**Comment by 0xg0nz0** [comment]
@anonrig I figured it out by reading your test case, problem very much between keyboard and chair, the test case was not properly handling base URL and so any test that depended on a well-formed base were failing. Thanks for making ada-url!
