### ISSUE TITLE
Extend the tests to include various systems...

### ISSUE THREAD

**Issue by lemire** [ada-url/ada#87]
The following seems like a minimum:

- [ ] old and new linux/gcc
- [ ] old and new linux/clang
- [ ] Visual Studio (old and new)
- [ ] Visual Studio+clang (old and new)

**Comment by anonrig** [comment]
Do you have a specific range for those systems? I’m not familiar with version ranges.

**Comment by lemire** [comment]
I recommend we try to support as wide a range as possible.

- GCC 8 should be tested.
- LLVM 6 should be tested.
- Visual Studio 2017  15.8 (MSVC 19.15) should be tested.
